// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TertiaryInstitutions.Data;

#nullable disable

namespace TertiaryInstitutions.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TertiaryInstitutions.Models.AssessmentSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ArtisticScore")
                        .HasColumnType("integer");

                    b.Property<int>("ConventionalScore")
                        .HasColumnType("integer");

                    b.Property<int>("EnterprisingScore")
                        .HasColumnType("integer");

                    b.Property<int>("InvestigativeScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("RealisticScore")
                        .HasColumnType("integer");

                    b.Property<string>("ResultCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SocialScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId");

                    b.ToTable("AssessmentSubmissions");
                });

            modelBuilder.Entity("TertiaryInstitutions.Models.JourneyProgress", b =>
                {
                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApplyCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("AssessCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EnrollCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExploreCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ShortlistCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LearnerId");

                    b.ToTable("JourneyProgresses");
                });

            modelBuilder.Entity("TertiaryInstitutions.Models.Learner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Track")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Learners", t =>
                        {
                            t.HasCheckConstraint("CK_Learner_Grade_Range", "\"Grade\" >= 8 AND \"Grade\" <= 12");
                        });
                });

            modelBuilder.Entity("TertiaryInstitutions.Models.SavedCareer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CareerId")
                        .HasColumnType("integer");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SavedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId", "CareerId")
                        .IsUnique();

                    b.ToTable("SavedCareers");
                });

            modelBuilder.Entity("TertiaryInstitutions.Models.AssessmentSubmission", b =>
                {
                    b.HasOne("TertiaryInstitutions.Models.Learner", null)
                        .WithMany("AssessmentSubmissions")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TertiaryInstitutions.Models.JourneyProgress", b =>
                {
                    b.HasOne("TertiaryInstitutions.Models.Learner", null)
                        .WithOne()
                        .HasForeignKey("TertiaryInstitutions.Models.JourneyProgress", "LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TertiaryInstitutions.Models.SavedCareer", b =>
                {
                    b.HasOne("TertiaryInstitutions.Models.Learner", null)
                        .WithMany()
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TertiaryInstitutions.Models.Learner", b =>
                {
                    b.Navigation("AssessmentSubmissions");
                });
#pragma warning restore 612, 618
        }
    }
}
